# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExponeaSDKMauiIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExponeaSDKMauiIOS
  pod "ExponeaSDK", "2.17.0"
  pod "ExponeaSDK-Notifications", "2.17.0"

  target 'ExponeaSDKMauiIOSTests' do
    # Pods for testing
  end

end
