target 'BloomreachSDKMauiIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BloomreachSDKMauiIOS
  pod "ExponeaSDK", "2.18.0"
  pod "ExponeaSDK-Notifications", "2.18.0"
  pod "AnyCodable-FlightSchool", "0.6.0"

  target 'BloomreachSDKMauiIOSTests' do
    # Pods for testing
    pod "Quick"
    pod "Nimble"
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']) < Gem::Version.new('11.0')
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
